"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path


# ============================================================
# FRAMEWORK SELECCIONADO
# ============================================================

# Framework seleccionado: Django.
# Se selecciona Django para el desarrollo web de Lucrier porque
# permite organizar el proyecto de forma estructurada y facilita
# la implementación de funcionalidades, rutas, vistas y conexión
# con la base de datos.


# ============================================================
# RUTAS DEL PROYECTO
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SEGURIDAD
# ============================================================

# Por ahora se mantiene la clave generada por Django.
# Antes de publicar el proyecto, deberá pasar a una variable
# de entorno y nunca quedar expuesta en GitHub.
SECRET_KEY = 'django-insecure-7chw&#cyaunbc@1bzs0f)!bw4%)j_d#snehenrh-d$&i3gb)k#'

DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APLICACIONES
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# CONFIGURACIÓN PRINCIPAL
# ============================================================

ROOT_URLCONF = 'config.urls'


# ============================================================
# PLANTILLAS
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Aquí posteriormente incorporaremos nuestra carpeta
        # templates/ del proyecto.
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# BASE DE DATOS
# ============================================================
#
# Django utilizará MySQL mediante mysqlclient.
#
# Los valores pueden configurarse mediante variables de entorno.
# Si todavía no existen, se utilizan estos valores locales:
#
# Base de datos: gestion_conjunto_residencial
# Usuario: root
# Contraseña: vacía
# Servidor: localhost
# Puerto: 3306
#
# IMPORTANTE:
# No ejecutaremos migraciones todavía.
# Primero comprobaremos la conexión con la base existente.
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        'NAME': os.getenv(
            'DB_NAME',
            'gestion_conjunto_residencial'
        ),

        'USER': os.getenv(
            'DB_USER',
            'root'
        ),

        'PASSWORD': os.getenv(
            'DB_PASSWORD',
            ''
        ),

        'HOST': os.getenv(
            'DB_HOST',
            'localhost'
        ),

        'PORT': os.getenv(
            'DB_PORT',
            '3306'
        ),

        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ============================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },
]


# ============================================================
# INTERNACIONALIZACIÓN
# ============================================================

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# ============================================================
# ARCHIVOS ESTÁTICOS
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]


# ============================================================
# CORREO ELECTRÓNICO
# ============================================================

MAILERS = {
    'default': {
        'BACKEND':
            'django.core.mail.backends.console.EmailBackend',
    },
}